### ISSUE TITLE
Spellchecker with LanguageTool?

### ISSUE THREAD

**Issue by aadrian** [JFormDesigner/markdown-writer-fx#10]
Hi,

I see that a spellchecker is on the todo list :) .

LanguageTool  https://languagetool.org/
https://github.com/languagetool-org/languagetool
seems to gain acceptance in many projects and is also Java based.

Any chance considering it for integration?

Thank you.

**Comment by JFormDesigner** [comment]
Yes, I'm already working on this on the [feature/spellchecker](https://github.com/JFormDesigner/markdown-writer-fx/tree/feature/spellchecker) branch.

Currently it always checks the whole text (which is slow) and includes markdown characters (which gives bad results). In the future I plan to check only changed paragraphs and exclude markdown characters. Correction suggestion and language download/selection is not yet implemented.

**Comment by JFormDesigner** [comment]
Made some progress on the [feature/spellchecker](https://github.com/JFormDesigner/markdown-writer-fx/tree/feature/spellchecker) branch:

- ignore markdown formatting characters in spell checking
- check only paragraphs, lists, block quotes and headings (ignore code blocks, tables, other)
- use wavy lines to highlight spelling problems in editor
- right-click on a problem shows a context menu with problem descriptions and suggested replacements

**Comment by aadrian** [comment]
@JFormDesigner The "spelling" functionality in that branch just looks great :) . 

IMHO it should be merged in master as it is, since it's a huge improvement .

Few tweaks that would also be nice:
 - allow to set/change the language
 - context menu size with corrections should not be bigger than the window: it's as big as the screen if there are many options.

**Comment by DevCharly** [comment]
Available in 1.0: https://github.com/JFormDesigner/markdown-writer-fx/releases
