### ISSUE TITLE
Combine cloud storage, git, external file editor as a notes app 

### ISSUE THREAD

**Issue by iwifigame** [JFormDesigner/markdown-writer-fx#15]
Now, cloud storage is very convenient. Everyone can use it as a synchronization tools.
Git can be used as a version manage tool which saved in cloud.
The external file editor as the edit application is very convenient to the users and manay of them is very powfull like vim.
So we just create a application which will show the markdown and manage the image(which stored in cloud) and manage the files.

**Comment by JFormDesigner** [comment]
Sorry, but cloud and git are out of scope of this project. An external editor does not make any sense because MW aims to be an editor.

What you seems to want is an Markdown preview application. MW is an Markdown editor (with preview).
