### ISSUE TITLE
Simplified Scrolling

### ISSUE THREAD

**Issue by DaveJarvis** [JFormDesigner/markdown-writer-fx#16]
Synchronized scrolling between the editor and preview pane uses complex logic in the following classes:

- WebViewPreview.java
- MarkdownPreviewPane.java (`scrollY` property, run later code, etc.)

Given the nature of Markdown, it is not possible to numerically compute the exact relative scroll position between the editor pane and the preview pane.

Instead, it is possible to insert a token in the markdown at the caret position, before rendering into HTML, that gets transformed into an empty `<span id="CARETPOSITION">` element. The scrolling logic reduces to, essentially:

```
  private static final String SCROLL_SCRIPT
    = "var e = document.getElementById('" + CARET_POSITION + "'); if( e != null ) { e.scrollIntoView(false); }";
```

This allows removal of the scrollY property, and eliminates the jittery-jumping that happens when typing at the end of the text. An example implementation might resemble:

```
public final class HTMLPreviewPane extends Pane {

  private static final String SCROLL_SCRIPT
    = "var e = document.getElementById('" + CARET_POSITION + "'); if( e != null ) { e.scrollIntoView(false); }";

  private final WebView webView = new WebView();
  private String html;
  private Path path;

  public HTMLPreviewPane( final Path path ) {
    setPath( path );
    initListeners();
    
    // Prevent tabbing into the preview pane.
    getWebView().setFocusTraversable( false );
  }

  public void update( final String html ) {
    setHtml( html );
    update();
  }

  private void update() {
    getEngine().loadContent(
      "<!DOCTYPE html>"
      + "<html>"
      + "<head>"
      + "<link rel='stylesheet' href='" + getClass().getResource( "pane.css" ) + "'>"
      + getBase()
      + "</head>"
      + "<body>"
      + getHtml()
      + "</body>"
      + "</html>" );
  }

  private String getBase() {
    final Path basePath = getPath();

    return basePath == null
      ? ""
      : ("<base href='" + basePath.getParent().toUri().toString() + "'>");
  }

  private void initListeners() {
    // Scrolls to the caret after the content has been loaded.
    getEngine().getLoadWorker().stateProperty().addListener(
      (ObservableValue<? extends State> observable,
        State oldValue, State newValue) -> {
        if( newValue == SUCCEEDED ) {
          scrollToCaret();
        }
      } );
  }

  private void scrollToCaret() {
    execute( SCROLL_SCRIPT );
  }

  private Object execute( final String script ) {
    return getEngine().executeScript( script );
  }

  private WebEngine getEngine() {
    return getWebView().getEngine();
  }

  public WebView getWebView() {
    return this.webView;
  }

  // ...other accessors...
}
```

Then, using the processors mentioned in issue #8, adding and replacing the special "caret position" with an empty `<span>` element becomes a simple matter of:

```
final Processor<String> hpp = new HTMLPreviewProcessor( previewPane );
final Processor<String> mcrp = new MarkdownCaretReplacementProcessor( hpp );
final Processor<String> mp = new MarkdownProcessor( mcrp );
final Processor<String> mcip = new MarkdownCaretInsertionProcessor( mp, fileEditorTab.getEditorPane().getEditor() );
final Processor<String> vnp = new VariableProcessor( mcip, getResolvedMap() );
final TextChangeProcessor tp = new TextChangeProcessor( vnp );
```

Note that there's another opportunity for simplification. Rather than a containment relationship between the FileEditor and its Tab, making a FileEditorTab subclass of Tab affords several opportunities to simplify the code base (such as eliminating the "PathProperty" in favour of adding listeners directly to the FileEditorTabPane, which also leverages inheritance, rather than composition, for providing the set of tabs).

**Comment by DaveJarvis** [comment]
Minor correction. Scrolling should attempt to center the caret position in the preview pane.

```
  /**
   * Scrolls to the caret position in the document.
   */
  private void scrollToCaret() {
    execute( getScrollScript() );
  }

  /**
   * Returns the JavaScript used to scroll the WebView pane.
   * 
   * @return A script that tries to center the view port on the CARET POSITION.
   */
  private String getScrollScript() {
    return "var e = document.getElementById('" + CARET_POSITION + "');"
      + "Element.prototype.documentOffsetTop = function () {"
      + "return this.offsetTop + ( this.offsetParent ? this.offsetParent.documentOffsetTop() : 0 );};"
      + "if( e != null ) { window.scrollTo( 0, e.documentOffsetTop() - (window.innerHeight / 2 ) ); }";
  }
```

**Comment by DaveJarvis** [comment]
To make this work, the "caret" must be positioned in the text such that it does not interfere with markdown. This can be accomplished as follows:

```
  public String processLink( final String t ) {
    int offset = getCaretPosition();
    final int length = t.length();

    // Insert the caret at the closest non-Markdown delimiter (i.e., the 
    // closest character from the caret position forward).
    while( offset < length && !isLetter( t.charAt( offset ) ) ) {
      offset++;
    }

    // Insert the caret position into the Markdown text, but don't interfere
    // with the Markdown iteself.
    return new StringBuilder( t ).replace(
      offset, offset, MD_CARET_POSITION ).toString();
  }
```

**Comment by JFormDesigner** [comment]
Interesting idea.

I had a look at the code and also tried Scrivenvar, but I see some disadvantages:
* requires to internally change markdown, parse markdown, render to html and update WebView (nearly) every time the user **simply moves the caret** (a no-go for me)
* synchronized scrolling (as currently in MW) no longer works
* when I move the caret a line down/up, then the preview jumps down/up to keep the current line in the preview center, even if the editor does not scroll and even if it is not necessary to scroll preview. This feels "bumpy" to me.

Another approach to achieve more precise sync scrolling would be injecting line numbers into HTML. But what if there is a long (e.g. 50 lines) paragraph and the line number is only injected at the beginning of the paragraph (e.g. `<p id="line-143">`). So it would be necessary to inject all line numbers into HTML. Not sure whether this works without interfere markdown...

I know that the synchronized scrolling, as currently implemented in MW, is not perfect. Especially when using images or longer text, then preview sometimes does not show the same part of the text as the editor. But most of the time it works OK. Good enough for a 1.0 release IMHO.

Anyway I'm curious to see whether you can refine this in Scrivenvar...

**Comment by DaveJarvis** [comment]
> requires to internally change markdown, parse markdown, render to html and update WebView (nearly) every time the user simply moves the caret (a no-go for me)

The view is re-rendered only when switching paragraphs. There are ways to expedite the change-parse-update cycle (e.g., only re-render the caret's current paragraph and previous paragraph), but that would require a lot of effort for not much gain. Flexmark is extraordinarily fast and can probably be optimized a bit more.

> synchronized scrolling (as currently in MW) no longer works

Broken due to refactoring. Planning to make scrolling the editor scroll the preview as well. For now, I'm okay with keyboard navigation (page up/down) instead of mousing.

> when I move the caret a line down/up, then the preview jumps down/up to keep the current line in the preview center, even if the editor does not scroll and even if it is not necessary to scroll preview.

This is a tricky one. The pseudo-caret position is inserted in the markdown at the closest position after the caret that will not affect the markdown syntax (technically, this still has a bug, but easily fixed by checking the AST). When at the bottom of the page, it's possible to be in a situation where the preview panel doesn't reflect the caret position. By centering the preview pane, it addresses this possibility. The downside is that, as you noticed, the preview becomes jumpy.

It can probably be addressed by a "scroll if needed" or "scroll into view" with a little logic to determine proximity to the bottom edge.

> Another approach to achieve more precise sync scrolling would be injecting line numbers into HTML.

That would smooth out the scrolling for Markdown-to-HTML editor, yet not suffice for an XML-to-Markdown-to-HTML editor. Injecting a pseudo-caret seems like the only way to ensure that the caret position in the editor is passed along to the preview, regardless of how many transformations take place between editing and previewing.
