### ISSUE TITLE
Markdown tables not rendered correctly.

### ISSUE THREAD

**Issue by aadrian** [JFormDesigner/markdown-writer-fx#17]
Markdown tables do not seem to be rendered correctly (as of today's latest commit).

E.g. 
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```
instead of being rendered:

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

will be:
![markdown_table_error](https://cloud.githubusercontent.com/assets/140953/21134887/1625d43a-c120-11e6-8165-18264f27fcd8.png)

**Comment by JFormDesigner** [comment]
That's because the Tables extensions is disabled.
Click the cog (in toolbar) or "Tools > Options > Markdown" and enable the Tables extension.

**Comment by aadrian** [comment]
> That's because the Tables extensions is disabled.
Click the cog (in toolbar) or "Tools > Options > Markdown" and enable the Tables extension.

I see, but than IMHO these two panels should display the same switches:

![all_settings](https://cloud.githubusercontent.com/assets/140953/21137090/af451a4c-c128-11e6-83ed-c8ecd65d8081.png)

and

![inline_settings](https://cloud.githubusercontent.com/assets/140953/21137098/b2f82508-c128-11e6-8af7-a31945472740.png)

**Comment by JFormDesigner** [comment]
They show the same options 😉
OK, the Options dialog additionally shows extensions that are not available for CommonMark (but for FlexMark).

The idea was to see all extensions supported by MW in the Options dialog and disable those extensions that are not available for the current markdown processor. The Cog on the other hand is for quick enable/disable extensions, where unavailable extensions are not interesting.

**Comment by aadrian** [comment]
> The idea was to see all extensions supported by MW in the Options dialog and disable those extensions that are not available for the current markdown processor. The Cog on the other hand is for quick enable/disable extensions, where unavailable extensions are not interesting.

I see :) .
