### ISSUE TITLE
Space after dead keys inserts a space.

### ISSUE THREAD

**Issue by tDwtp** [JFormDesigner/markdown-writer-fx#20]
In all Editors I know, pressing space after hitting a dead-key (like '&grave;', '&acute;' or '^') will result in a single character.

However, in Markdown Writer FX it always puts an additional space afterwads, which is epecially annoying when writing code examples on an european keyboard. '&grave;' + 'a' => '&agrave;' or tripple-'&grave;' + space makes language selection annoying.

**Comment by JFormDesigner** [comment]
Yes, the extra space character annoys me too.
It is a bug in JavaFX, but finally I've found a workaround 😄 

Fixed in 0.9
