### ISSUE TITLE
Gradle Application Plug-in!

### ISSUE THREAD

**Issue by aadrian** [JFormDesigner/markdown-writer-fx#21]
Please add the Gradle Application Plug-in https://docs.gradle.org/current/userguide/application_plugin.html to generate the distribution and the platform dependent shell scripts. 

IMHO it's much better than the used ```java-library-distribution```

Thank you.

**Comment by JFormDesigner** [comment]
Thanks for the tip. I'll have a look, but in the long-term, I'm looking for an easy (hosted/cloud) solution to build a self-contained application (including JRE, installer, exe/app ) for Windows, macOS and Linux, which would it make much easier to use Markdown Writer FX for unexperienced users.

**Comment by aadrian** [comment]
Travis CI? It's free for open source projects, and can push artifacts back (and to maven central)

**Comment by aadrian** [comment]
If you want to provide installers too, these projects solved it with Gradle like this:
 - https://github.com/freeplane/freeplane
 - https://github.com/mucommander/mucommander

but it's more work. IMHO the 'application' plug-in offers the best results for the least amount of work: just include and specify the main class, and this will provide a portable solution for all platforms with start scripts.

**Comment by aadrian** [comment]
@JFormDesigner https://github.com/JFormDesigner/markdown-writer-fx/pull/30 until native installers are provided.

**Comment by JFormDesigner** [comment]
merged PR #30

Thanks.
