### ISSUE TITLE
Scroll in preview pane locked when Maximized, minimized and restored

### ISSUE THREAD

**Issue by SMontgomery** [JFormDesigner/markdown-writer-fx#23]
## Description
Scroll for the preview pane gets locked if you minimize from a maximized state and then bring it back up.

## Versions
Markdown Writer FX v0.9
Windows 10.0.14393
Java 1.8.0_102

## Reproduction Steps
1. Maximize application (Scroll should work fine)
2. Minimize application
3. Restore application (click on it in task bar)

Result, scrolling is locked for preview pane.  To fix, just resize.

**Comment by JFormDesigner** [comment]
@SMontgomery thanks for the detailed bug report 👍 

This is a bug in JavaFX, but it has been **fixed in Java 8u131**.
