### ISSUE TITLE
Duplication of icon

### ISSUE THREAD

**Issue by DaveJarvis** [JFormDesigner/markdown-writer-fx#3]
MainWindow.java:

		alert.setGraphic(new ImageView(new Image("org/markdownwriterfx/markdownwriterfx32.png")));

MarkdownWriterFXApp:

				new Image("org/markdownwriterfx/markdownwriterfx16.png"),
				new Image("org/markdownwriterfx/markdownwriterfx32.png"),
				new Image("org/markdownwriterfx/markdownwriterfx128.png"),
				new Image("org/markdownwriterfx/markdownwriterfx256.png"),
				new Image("org/markdownwriterfx/markdownwriterfx512.png"));

These should be replaced with a single SVG file and generated dynamically as needed, if even necessary (an SVG should scale beautifully).

**Comment by JFormDesigner** [comment]
Not sure how this should work because JavaFX Image class does not support SVG.

Anyway found out that JavaFX uses only 32x32 or 128x128 images.
So I've removed the other 3 images in commit cde7444334767c59f6b2f46d2705c5a3b2bab6fb

**Comment by DaveJarvis** [comment]
Could be part of the build process. Either using gradle to leverage the Apache Batik library, or at run time using the same library. 

http://thinktibits.blogspot.ca/2012/12/Batik-Convert-SVG-PNG-Java-Program-Example.html

[logo.svg.txt](https://github.com/JFormDesigner/markdown-writer-fx/files/537684/logo.svg.txt)

See attached.

**Comment by DaveJarvis** [comment]
Such as...

```
#!/bin/bash

INKSCAPE=/usr/bin/inkscape

declare -a SIZES=("16" "32" "64" "128" "256" "512")

for i in "${SIZES[@]}"; do
  # -y: export background opacity 0
  $INKSCAPE -y 0 -z -f "logo.svg" -w "${i}" -e "logo${i}.png"
done
```

**Comment by JFormDesigner** [comment]
I've re-created Markdown Writer FX logo in SVG (used Inkscape) and exported markdownwriterfx*.png from SVG in 2c2e73296e4c364c2fbaca74a0d281a7cdef1c04

Thanks for the Inkscape script. Didn't know that Inkscape supports this.

Anyway, since now we need only two sizes (32 and 128), I don't see a need to create the PNGs as part of the build script (or at runtime, which would require shipping Batik library).
