### ISSUE TITLE
Pulling parts of MarkdownWriterFX into another application

### ISSUE THREAD

**Issue by DonyorM** [JFormDesigner/markdown-writer-fx#32]
I'm currently making an application where I would like to integrate markdown editing and rendering similar to the way MarkdownWriterFX. Are you guys cool with me pulling classes/large chunks of code from MarkdownWriterFX into this other application?

I would just add it as a dependency, but I really only need the editor pane and the preview pane (for displaying the result), not any of the export features or the stages.

**Comment by JFormDesigner** [comment]
Sure, it is open source and the [LICENSE](https://github.com/JFormDesigner/markdown-writer-fx/blob/master/LICENSE) allows you to use/copy code 👍

**Comment by DonyorM** [comment]
Cool. Would you be interested in separating out the core components into a library that this application depends on? I'm not real familiar with the codebase, but it seems like there's a fair amount that could be separate but still useful. I would be willing to do most of the work for the initial separation then pass off the repository to you all.

**Comment by DonyorM** [comment]
@JFormDesigner Any thoughts on making a JavaFX markdown library?
