### ISSUE TITLE
Web View Preview: Separation of Concerns

### ISSUE THREAD

**Issue by DaveJarvis** [JFormDesigner/markdown-writer-fx#8]
The `WebViewPreview` update method takes a `Renderer renderer` that is used, ultimately, to present an HTML page using `renderer.getHtml()`.

This coupling seems to violate the [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns). That is, the WebViewPreview should not be coupled, in any way, to knowledge of Markdown (i.e., how the HTML is generated). Rather, the WebViewPreview should only be concerned with what HTML is to be displayed, without any dependency on Markdown.

Separating these concerns would allow the interjection of code that performs other manipulations on the Markdown prior to the Web View displaying it. This change would allow for a number of possibilities prior to conversion, including:

- Pass the Markdown to an R processing engine ([Rmd](http://rmarkdown.rstudio.com/))
- Pre-parse variables in the Markdown
- Edit and transform an XML document into Markdown
- Any combination of the above

This could be facilitated by the implication of a simple [chain-of-command](https://github.com/DaveJarvis/scrivenvar/tree/master/src/main/java/com/scrivenvar/processors) pattern, with the WebViewPreview pane being the last link in the chain.

**Comment by JFormDesigner** [comment]
Sorry, but `WebViewPreview` does not have any knowledge of Markdown. It only knows the `Renderer` interface. The two implementations of this interface have the Markdown knowledge.

**Comment by DaveJarvis** [comment]
`import org.markdownwriterfx.preview.MarkdownPreviewPane.Renderer;`

The `WebViewPreview` uses a `MarkdownPreviewPane.Renderer`, which directly renders the markdown into HTML (or AST). While the Renderer itself is generic, there's no opportunity to send the Markdown text through a chain-of-command, which would allow for multiple processors to takes turns processing the text. This implies that the editor content is tightly coupled to the preview pane (i.e., changing one requires changes to the other).
