### ISSUE TITLE
Syntax highlighting for code snippets.

### ISSUE THREAD

**Issue by aadrian** [JFormDesigner/markdown-writer-fx#9]
Please add syntax highlighting for the code snippets too, depending on the used language: in the editor but also in the output.

Thank you.

**Comment by JFormDesigner** [comment]
Thanks, good idea. I'm missing this too...

Any recommendation for a good syntax highlighting library (written in Java)?

**Comment by aadrian** [comment]
> Any recommendation for a good syntax highlighting library (written in Java)?

Isn't RichTextFX capable of that (since it does for for markdown) ?

For the parsing and AST part, ANTLR https://github.com/antlr/antlr4 seems to have the most and detailed ready grammars: https://github.com/antlr/grammars-v4

**Comment by JFormDesigner** [comment]
> > Any recommendation for a good syntax highlighting library (written in Java)?
>
> Isn't RichTextFX capable of that (since it does for for markdown) ?

Sure, for displaying 😉 
My questions was regarding a library that parses code and outputs "highlighted" code

ANTLR seems to be overkill for syntax highlighting...

Did a quick search and found:
- https://bitbucket.org/hski/java-syntax-highlighter
- https://github.com/tliron/jygments
- http://stackoverflow.com/questions/221570/what-code-highlighting-libs-are-there-for-java

Another alternative would be to use [highlight.js](https://highlightjs.org/), which is written in JavaScript. For the preview, this would be probably easy because the preview is a WebKit component that natively supports JavaScript. For the editor, I could try to use Java Nashorn...

**Comment by aadrian** [comment]
> Another alternative would be to use highlight.js, 

There are many JS based highlighters. E.g.
https://webdesign.tutsplus.com/articles/25-syntax-highlighters-tried-and-tested--cms-23931

>  this would be probably easy because the preview is a WebKit component that natively supports JavaScript. For the editor, I could try to use Java Nashorn...

Well, in that case maybe for a first version, having only for the **preview** would be a good start :) .

**Comment by JFormDesigner** [comment]
@aadrian thanks for the link to the 25 JS highlighters. This was really helpful. Tried some of them and decided to use Prism. For the **preview** only. The code is now in the master branch. Give it a try 😉 

I'll keep this issue open for the syntax highlighting in the editor.

**Comment by aadrian** [comment]
> Tried some of them and decided to use Prism.

Good choice.

Even if https://github.com/PrismJS/prism does not have so many languages supported (yet), the project is active and there's also "plug-in" support for further extensions.

> The code is now in the master branch. Give it a try

The integration looks very good :) .
Can't imagine now using without without this feature, so when this version is released, the screenshots https://github.com/JFormDesigner/markdown-writer-fx/blob/master/images/screenshot.png could show that feature too :) .


> For the **preview** only.

Now that it works so nicely for **preview**, it could be interesting to try to apply it to **HTML Source** and **Markdown AST** too, since those are also read only :) ?

**Comment by JFormDesigner** [comment]
> Now that it works so nicely for preview, it could be interesting to try to apply it to HTML Source and Markdown AST too, since those are also read only :) ?

Yes, had this in mind too. Now implemented in master 😉 

I've also implemented "range highlighting" in the Markdown AST view, which makes it much easier to find the AST that is at the caret in the editor.

Now that we have syntax highlighting in HTML Source view, I think I should also implement it for HTML blocks/inlines in the editor (before releasing a new version)...

**Comment by aadrian** [comment]
> > Now that it works so nicely for preview, it could be interesting to try to apply it to HTML Source and Markdown AST too, since those are also read only :) ?

> Now implemented in master 

It looks very good :) .
Now it's much easier to spot possible problems too :) , e.g. #17

**Comment by JFormDesigner** [comment]
Syntax highlighting for HTML/XML/SVG/MathML in editor is now implemented in master

**Comment by aadrian** [comment]
The editor is simply fantastic with syntax highlighting !

It needs however a shorter name that is more SEO friendly :)
